# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst
sudo: required 
services:
  - docker
language: generic 
compiler:
  - gcc
notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
      - gm130s@gmail.com
env:
  matrix:
    - ROS_DISTRO="kinetic"   ROS_REPO=ros ABICHECK_URL='github:ros-drivers/openni2_camera#indigo-devel'
    - ROS_DISTRO="kinetic"   PRERELEASE=true
    - ROS_DISTRO="melodic"   ROS_REPO=ros ABICHECK_URL='github:ros-drivers/openni2_camera#indigo-devel' ABICHECK_MERGE=auto
    - ROS_DISTRO="melodic"   PRERELEASE=true
    - ROS_DISTRO="noetic"   ROS_REPO=ros ABICHECK_URL='github:ros-drivers/openni2_camera#indigo-devel' ABICHECK_MERGE=auto
    - ROS_DISTRO="noetic"   PRERELEASE=true
matrix:
  allow_failures:
    - env: ROS_DISTRO="kinetic"   PRERELEASE=true
    - env: ROS_DISTRO="melodic"   PRERELEASE=true
    - env: ROS_DISTRO="noetic"   PRERELEASE=true
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git -b master .ci_config
script:
  - source .ci_config/travis.sh
#  - source ./travis.sh  # Enable this when you have a package-local script 
