//#line 2 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the pico_zense_camera package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __pico_zense_camera__PICO_ZENSE_DCAM710CONFIG_H__
#define __pico_zense_camera__PICO_ZENSE_DCAM710CONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace pico_zense_camera
{
  class pico_zense_dcam710ConfigStatics;

  class pico_zense_dcam710Config
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(pico_zense_dcam710Config &config, const pico_zense_dcam710Config &max, const pico_zense_dcam710Config &min) const = 0;
      virtual void calcLevel(uint32_t &level, const pico_zense_dcam710Config &config1, const pico_zense_dcam710Config &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, pico_zense_dcam710Config &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const pico_zense_dcam710Config &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pico_zense_dcam710Config &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const pico_zense_dcam710Config &config) const = 0;
      virtual void getValue(const pico_zense_dcam710Config &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T pico_zense_dcam710Config::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T pico_zense_dcam710Config::* field;

      virtual void clamp(pico_zense_dcam710Config &config, const pico_zense_dcam710Config &max, const pico_zense_dcam710Config &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const pico_zense_dcam710Config &config1, const pico_zense_dcam710Config &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, pico_zense_dcam710Config &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const pico_zense_dcam710Config &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, pico_zense_dcam710Config &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const pico_zense_dcam710Config &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const pico_zense_dcam710Config &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, pico_zense_dcam710Config &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, pico_zense_dcam710Config &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<pico_zense_dcam710Config::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(pico_zense_dcam710Config &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("depth_confidence_threshold"==(*_i)->name){depth_confidence_threshold = boost::any_cast<int>(val);}
        if("depth_range"==(*_i)->name){depth_range = boost::any_cast<double>(val);}
        if("rgb_resolution"==(*_i)->name){rgb_resolution = boost::any_cast<std::string>(val);}
      }
    }

    int depth_confidence_threshold;
double depth_range;
std::string rgb_resolution;

    bool state;
    std::string name;

    
}groups;



//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int depth_confidence_threshold;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double depth_range;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string rgb_resolution;
//#line 228 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("pico_zense_dcam710Config::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const pico_zense_dcam710Config &__max__ = __getMax__();
      const pico_zense_dcam710Config &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const pico_zense_dcam710Config &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const pico_zense_dcam710Config &__getDefault__();
    static const pico_zense_dcam710Config &__getMax__();
    static const pico_zense_dcam710Config &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const pico_zense_dcam710ConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void pico_zense_dcam710Config::ParamDescription<std::string>::clamp(pico_zense_dcam710Config &config, const pico_zense_dcam710Config &max, const pico_zense_dcam710Config &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class pico_zense_dcam710ConfigStatics
  {
    friend class pico_zense_dcam710Config;

    pico_zense_dcam710ConfigStatics()
    {
pico_zense_dcam710Config::GroupDescription<pico_zense_dcam710Config::DEFAULT, pico_zense_dcam710Config> Default("Default", "", 0, 0, true, &pico_zense_dcam710Config::groups);
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.depth_confidence_threshold = 0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.depth_confidence_threshold = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.depth_confidence_threshold = 100;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pico_zense_dcam710Config::AbstractParamDescriptionConstPtr(new pico_zense_dcam710Config::ParamDescription<int>("depth_confidence_threshold", "int", 0, "Depth distance confidance (0% keeps all, 100% drops every depth point with <100% confidence", "", &pico_zense_dcam710Config::depth_confidence_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pico_zense_dcam710Config::AbstractParamDescriptionConstPtr(new pico_zense_dcam710Config::ParamDescription<int>("depth_confidence_threshold", "int", 0, "Depth distance confidance (0% keeps all, 100% drops every depth point with <100% confidence", "", &pico_zense_dcam710Config::depth_confidence_threshold)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.depth_range = 0.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.depth_range = 15.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.depth_range = 1.0;
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pico_zense_dcam710Config::AbstractParamDescriptionConstPtr(new pico_zense_dcam710Config::ParamDescription<double>("depth_range", "double", 0, "Optimise the camera for this depth range", "", &pico_zense_dcam710Config::depth_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pico_zense_dcam710Config::AbstractParamDescriptionConstPtr(new pico_zense_dcam710Config::ParamDescription<double>("depth_range", "double", 0, "Optimise the camera for this depth range", "", &pico_zense_dcam710Config::depth_range)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.rgb_resolution = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.rgb_resolution = "";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.rgb_resolution = "1280x720";
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(pico_zense_dcam710Config::AbstractParamDescriptionConstPtr(new pico_zense_dcam710Config::ParamDescription<std::string>("rgb_resolution", "str", 0, "RGB Resolution", "{'enum_description': 'List of supported resolutions', 'enum': [{'srcline': 12, 'description': 'Max Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '1920x1080', 'ctype': 'std::string', 'type': 'str', 'name': '1920x1080'}, {'srcline': 13, 'description': 'Default Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '1280x720', 'ctype': 'std::string', 'type': 'str', 'name': '1280x720'}, {'srcline': 14, 'description': 'Depth Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '640x480', 'ctype': 'std::string', 'type': 'str', 'name': '640x480'}, {'srcline': 15, 'description': 'Min Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '640x360', 'ctype': 'std::string', 'type': 'str', 'name': '640x360'}]}", &pico_zense_dcam710Config::rgb_resolution)));
//#line 291 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(pico_zense_dcam710Config::AbstractParamDescriptionConstPtr(new pico_zense_dcam710Config::ParamDescription<std::string>("rgb_resolution", "str", 0, "RGB Resolution", "{'enum_description': 'List of supported resolutions', 'enum': [{'srcline': 12, 'description': 'Max Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '1920x1080', 'ctype': 'std::string', 'type': 'str', 'name': '1920x1080'}, {'srcline': 13, 'description': 'Default Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '1280x720', 'ctype': 'std::string', 'type': 'str', 'name': '1280x720'}, {'srcline': 14, 'description': 'Depth Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '640x480', 'ctype': 'std::string', 'type': 'str', 'name': '640x480'}, {'srcline': 15, 'description': 'Min Resolution', 'srcfile': '/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg', 'cconsttype': 'const char * const', 'value': '640x360', 'ctype': 'std::string', 'type': 'str', 'name': '640x360'}]}", &pico_zense_dcam710Config::rgb_resolution)));
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 246 "/opt/ros/melodic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(pico_zense_dcam710Config::AbstractGroupDescriptionConstPtr(new pico_zense_dcam710Config::GroupDescription<pico_zense_dcam710Config::DEFAULT, pico_zense_dcam710Config>(Default)));
//#line 366 "/opt/ros/melodic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<pico_zense_dcam710Config::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<pico_zense_dcam710Config::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<pico_zense_dcam710Config::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    pico_zense_dcam710Config __max__;
    pico_zense_dcam710Config __min__;
    pico_zense_dcam710Config __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const pico_zense_dcam710ConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static pico_zense_dcam710ConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &pico_zense_dcam710Config::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const pico_zense_dcam710Config &pico_zense_dcam710Config::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const pico_zense_dcam710Config &pico_zense_dcam710Config::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const pico_zense_dcam710Config &pico_zense_dcam710Config::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<pico_zense_dcam710Config::AbstractParamDescriptionConstPtr> &pico_zense_dcam710Config::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<pico_zense_dcam710Config::AbstractGroupDescriptionConstPtr> &pico_zense_dcam710Config::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const pico_zense_dcam710ConfigStatics *pico_zense_dcam710Config::__get_statics__()
  {
    const static pico_zense_dcam710ConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = pico_zense_dcam710ConfigStatics::get_instance();

    return statics;
  }

//#line 12 "/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg"
      const char * const pico_zense_dcam710_1920x1080 = "1920x1080";
//#line 13 "/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg"
      const char * const pico_zense_dcam710_1280x720 = "1280x720";
//#line 14 "/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg"
      const char * const pico_zense_dcam710_640x480 = "640x480";
//#line 15 "/home/alex/Alex_documents/RGCNN_git/Vizualization_demos/RGCNN_demo_ws/src/pico_zense_camera/cfg/pico_zense_dcam710.cfg"
      const char * const pico_zense_dcam710_640x360 = "640x360";
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __PICO_ZENSE_DCAM710RECONFIGURATOR_H__
